### ISSUE TITLE
Path separators are hardcoded

### ISSUE THREAD

**Issue by cjharries-nexient** [jaxxstorm/aws-sso-creds#10]
I'm trying to use `aws-sso-creds` in a fairly restricted work environment. I need a POSIX shell and can't install WSL so I'm trying to use Cygwin. When I run `export`, I get this.

<img width="650" alt="Screen Shot 2022-10-10 at 2 51 52 PM" src="https://user-images.githubusercontent.com/97557000/194942269-11364bf2-8dd3-4803-806e-42b26ced5210.png">

The issue [is here](https://github.com/jaxxstorm/aws-sso-creds/blob/master/pkg/config/config.go#L13). The code has hardcoded POSIX path separators instead of using an agnostic function (AFAIK [this is the preferred method](https://pkg.go.dev/path/filepath#Join)). I'll have a PR up for this later today or this week and I'll try to find all other path instances.

**Comment by jaxxstorm** [comment]
Thanks for the issue, I'll try spin up a windows environment to get this fixed
