### ISSUE TITLE
My cache files don't look like that

### ISSUE THREAD

**Issue by anentropic** [jaxxstorm/aws-sso-creds#46]
It looks like this tool implements the method shown here: https://repost.aws/knowledge-center/sso-temporary-credentials

However my cache files don't look like that:

```sh
$ cat ~/.aws/sso/cache/a48225c844ae1255f992c3ecb18ac26d0bf5e6cd.json
{"clientId": "...", "clientSecret": "...", "expiresAt": "2023-12-24T12:28:37Z", "scopes": ["sso:account:access"]}
```

no `startUrl` or `accessToken` values

Any idea what's up?

**Comment by jaxxstorm** [comment]
Unfortunately not, I'd reach out to AWS or another support option
